name: kriyeta_event_manage
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  fpdart: ^0.6.0
  google_fonts: ^4.0.0
  google_sign_in: ^6.1.4
  lottie: ^2.4.0
  flutter_native_splash: ^2.3.1
  video_thumbnail: ^0.5.3
  image_picker: ^0.8.8
  get: ^4.6.5
  flutter_svg: ^2.0.6
  dotted_border: ^2.0.0+3
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

flutter_native_splash:
  color: "#ffffff"

flutter_launcher_icons:
  android: 'launch_icon'
  image_path: "assets/images/logo.png"